sudo: required
services:
  - docker

before_install:
  - docker build -t danlee0150/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true danlee0150/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-nginx'
  env: 'DockerNginx-env'
  bucket_name: 'elasticbeanstalk-us-east-2-976188958134'
  bucket_path: 'docker-nginx'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
