version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules #dont map this
      - .:/app #map this notice the (:)
    environment:
      - CHOKIDAR_USEPOLLING=true # to let react recompile every time there is changes from outside container
  react-app-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ['npm', 'run', 'test']
